services:
  - type: web
    name: youtube-to-mp3
    env: python
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: gunicorn server:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: PATH
        value: /opt/render/project/bin:${PATH}
    plan: free 